### ISSUE TITLE
Server shuts down?

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [dran1x/CS2-AutoUpdater#1]
I think my server is crashing with this.. Or the plugin sends quit, and it doesn't restart again after that?
Any way to get logs to see whats going on?

CS2AutoUpdater 1.0.2
counterstrikesharp-build-16

With this in my command line:
-autoupdate -steam_dir ~/csgo -steamcmd_script ~/csgo/retakes1.txt

@ShutdownOnFailedCommand 1
@NoPromptForPassword 1
login anonymous 
force_install_dir /home/retakes1
app_update 730
quit

**Comment by dran1x** [comment]
It's supposed to detect an update and shut down the server. Ideally you would want your servers to restart automatically if they suddenly go down due to an unexpected server crash, then on startup, SteamCMD checks for updates, which is what Pterodactyl does.

I've only implemented console logs for now, but I'll work on adding file logs tomorrow.

**Comment by BrutalCSEjziponken** [comment]
Seems like they removed the _restart command that worked in CSGO? So now there is only quit, which closes the server. I don't have Pterodactyl. I just run the server in screen like I always have.

**Comment by creazy231** [comment]
I guess there is a bug.. latest release makes the server to shut down / restart like every 5 minutes with these logs:
```
cs2-dedicated  | [CS2AutoUpdater] New Counter-Strike 2 update released (Build: 13968)
cs2-dedicated  | [CS2AutoUpdater] Restarting the server due to the new game update. (Build: 13968)
```

**Comment by BrutalCSEjziponken** [comment]
> I guess there is a bug.. latest release makes the server to shut down / restart like every 5 minutes with these logs:
> 
> ```
> cs2-dedicated  | [CS2AutoUpdater] New Counter-Strike 2 update released (Build: 13968)
> cs2-dedicated  | [CS2AutoUpdater] Restarting the server due to the new game update. (Build: 13968)
> ```

Maybe its detecting a client update and keeps updating? :)

**Comment by dran1x** [comment]
I think I may have uploaded the wrong binary..My test binary. I will look into this when I'm home.

If one of you guys could build from source and test that version, that would be helpful.

**Comment by dran1x** [comment]
@BrutalCSEjziponken @creazy231 I went ahead and uploaded the correct release binary. Download the [latest release](https://github.com/dran1x/CS2-AutoUpdater/releases/latest).

**Comment by BrutalCSEjziponken** [comment]
@dran1x That didnt fix my issue. After a while my server was shut down again.

**Comment by dran1x** [comment]
@BrutalCSEjziponken I've released an [update](https://github.com/dran1x/CS2-AutoUpdater/releases/latest) that includes file logging. Would you mind trying that version to see if the issue persists?

**Comment by BrutalCSEjziponken** [comment]
> @BrutalCSEjziponken I've released an [update](https://github.com/dran1x/CS2-AutoUpdater/releases/latest) that includes file logging. Would you mind trying that version to see if the issue persists?

Finally had time to test the latest. Seems to work, no shut downs in a few hours.
