### ISSUE TITLE
[BUG] Even though cvar is disabled, the message is still sent.

### ISSUE THREAD

**Issue by crashzk** [dran1x/CS2-AutoUpdater#11]
```
2024-03-25 15:16:04.276 -03:00 [INFO] plugin:AutoUpdater ConVar 'sv_hibernate_when_empty' is enabled. This plugin may not work as expected
```

![image](https://github.com/dran1x/CS2-AutoUpdater/assets/32937653/f1c4d5a9-1271-4de8-95af-962f8a3977b3)

```
[#19:LOADED]: "AutoUpdater" (1.0.4) by dranix
Auto Updater for Counter-Strike 2.
```

@dran1x

**Comment by dran1x** [comment]
Please run the command once the server is fully initialized. If it shows as 'false', then everything is working properly. This is just a message that will print out when hibernation is changed or set, and your server configuration files might not have had a chance yet to be executed. I'll change the way I check for this in a later update.
