### ISSUE TITLE
Server shutdown while latest

### ISSUE THREAD

**Issue by b-zee** [dran1x/CS2-AutoUpdater#2]
```
[CS2AutoUpdater] New Counter-Strike 2 update released (Build: 13968)                                                                                   
[CS2AutoUpdater] Restarting the server due to the new game update. (Build: 13968)
```

But output of `status` includes:
```
version  : 1.39.6.8/13968 9842 secure  public
```

Before launch, SteamCMD's `app_update` is always run and shows:
```
Success! App '730' already up to date.
```

The `steam.inf` file reads:
```
ClientVersion=2000188
ServerVersion=2000188
PatchVersion=1.39.6.8
ProductName=cs2
appID=730
ServerAppID=<redacted>
SourceRevision=8483395
VersionDate=Nov 09 2023
VersionTime=17:22:26
```

**Comment by dran1x** [comment]
I believe you might have also downloaded the debug binary I accidentally uploaded for version 1.0.2. Could you please update to the [latest version](https://github.com/dran1x/CS2-AutoUpdater/releases/latest)?

**Comment by b-zee** [comment]
@dran1x, I will try the latest version asap. Thanks a lot for your work on this!
