### ISSUE TITLE
Issue with the update

### ISSUE THREAD

**Issue by rcon420** [dran1x/CS2-AutoUpdater#3]
CS2 just got changes to [SteamDB Unknown App 2275530](https://steamdb.info/app/2275530/history/?changeid=21065092)
Changelist 21065092  and plugin issued reboot becuase it was thinking there is game update but its not even released  you should change the method how updates are detected.

**Comment by mrc4tt** [comment]
Can you please post the output from the `css_plugins list`?

Have you tested v1.0.2?
**It works here, probably I'm on pterodactyl**

**Comment by rcon420** [comment]
> Can you please post the output from the `css_plugins list`?
> 
> Have you tested v1.0.2? **It works here, probably I'm on pterodactyl**

yes tested on v.1.02,  
![image](https://github.com/dran1x/CS2-AutoUpdater/assets/47292145/c66dcc8d-5753-4d92-9838-663479ac5070)
i saw it with my own eyes that it exucuted server update while there was no game update. 

also this plugin crashes server after while removed all the plugins and this one  was still crashing the server.

**Comment by mrc4tt** [comment]
> yes tested on v.1.02, ![image](https://user-images.githubusercontent.com/47292145/282182946-c66dcc8d-5753-4d92-9838-663479ac5070.png) i saw it with my own eyes that it exucuted server update while there was no game update.
> 
> also this plugin crashes server after while removed all the plugins and this one was still crashing the server.

At first glance, I don't see the same thing on my test server, and I don't see a crash in any other way.

**Comment by dran1x** [comment]
@rcon420 I've just released an [updated version](https://github.com/dran1x/CS2-AutoUpdater/releases/latest) with file logging. I accidentally uploaded the debug binary, which you might have downloaded. I fixed this issue just a couple of minutes ago.

**Comment by rcon420** [comment]
> @rcon420 I've just released an [updated version](https://github.com/dran1x/CS2-AutoUpdater/releases/latest) with file logging. I accidentally uploaded the debug binary for 1.0.2, which you might have downloaded. I fixed this issue just a couple of minutes ago.

I been afk for some time  in the server so far i don't see any crashes anymore with the new version

**Comment by mrc4tt** [comment]
> I been afk for some time in the server so far i don't see any crashes anymore with the new version

If it works for you, i will recommend closing the issue :+1:
